### ISSUE TITLE
panic analyzing old cluster

### ISSUE THREAD

**Issue by theRealWardo** [derailed/popeye#10]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
when analyzing my kubernetes cluster, I get a panic. if you can provide some pointers, I'm happy to try and fix this bug so that it works for us.

```
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x206ba85, 0x1, 0xfffffffffffffffc, 0xc0006e3d60, 0x3)
        /usr/local/Cellar/go/1.12.1/libexec/src/strings/strings.go:533 +0x5ca
github.com/derailed/popeye/internal/report.Write(0x2248c60, 0xc00081e440, 0x1, 0x1, 0xc000f968c0, 0x4f)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/report/writer.go:81 +0x19c
github.com/derailed/popeye/pkg.(*Popeye).printReport(0xc0008bdd40, 0x681c518, 0xc00000e160, 0xc0000db99c, 0x4)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:130 +0x7a5
github.com/derailed/popeye/pkg.(*Popeye).Sanitize(0xc0008bdd40)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:74 +0x4e4
github.com/derailed/popeye/cmd.doIt(0x2db09a0, 0x2ddbcd8, 0x0, 0x0)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:56 +0xdf
github.com/spf13/cobra.(*Command).execute(0x2db09a0, 0xc0000b2000, 0x0, 0x0, 0x2db09a0, 0xc0000b2000)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x2db09a0, 0x0, 0x0, 0xc0003e5f88)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/derailed/popeye/cmd.Execute()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:43 +0x32
main.main()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/main.go:19 +0x20
```

**To Reproduce**
1. connect to my old cluster
2. run popeye
3. panic

**Expected behavior**
I get a full report.

**Versions (please complete the following information):**
 - OS: [e.g. OSX] - OSX
 - Popeye [e.g. 0.1.0] - 0.1.2
 - K8s [e.g. 1.11.0] - 1.8.15

**Comment by derailed** [comment]
@theRealWardo Tx for reporting this and for your help!! 

I think this issue was resolved via @vdesjardins kind PR. 
Can you upgrade Popeye and see if you can make it farther?

Closing for now. Please re-open if that's not the case. Tx!!

**Comment by theRealWardo** [comment]
yep works now! thanks!
