### ISSUE TITLE
No RunInfo in context

### ISSUE THREAD

**Issue by aschleifer** [derailed/popeye#280]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
When running popeye version 0.20.0 without any pramaters I get this error:

```
 ___     ___ _____   _____                       D          .-'-.
| _ \___| _ \ __\ \ / / __|                       O     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         H   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  X     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |


Boom! Doh! No RunInfo in context
```

**To Reproduce**
Run `popeye` with an active kubecontext without any parameters

**Expected behavior**
It should generate the normal linting output.

**Versions (please complete the following information):**
 - OS: Arch Linux
 - Popeye 0.20.0
 - K8s 1.28.4

**Comment by derailed** [comment]
@aschleifer Thanks for the heads up Andreas! Could you share the popeye's logs? 
Do you get the same error if you specify a namespace aka `popeye -n default`?

**Comment by aschleifer** [comment]
> @aschleifer Thanks for the heads up Andreas! Could you share the popeye's logs? Do you get the same error if you specify a namespace aka `popeye -n default`?

Hello, yes the error also occures when giving a namespace. Here are the logs:

```
4:52PM DBG Connecting to API Server [redacted]
4:52PM DBG Lint 38.157884ms
4:52PM ERR Doh! No RunInfo in context
4:52PM ERR goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/derailed/popeye/cmd.doIt.func1()
        github.com/derailed/popeye/cmd/root.go:61 +0x10f
panic({0x651639434400?, 0x651639851af0?})
        runtime/panic.go:770 +0x132
github.com/derailed/popeye/internal.MustExtractRunInfo(...)
        github.com/derailed/popeye/internal/context.go:55
github.com/derailed/popeye/internal/issues.(*Collector).AddErr(0xc000595098, {0x651639875d68?, 0xc000648630?}, {0xc00089b100, 0x1, 0x77abd740283a6bc?})
        github.com/derailed/popeye/internal/issues/collector.go:97 +0x32d
github.com/derailed/popeye/internal/scrub.NewCluster({0x651639875d68, 0xc000648630}, 0xc000648870, 0xc00050e0b0)
        github.com/derailed/popeye/internal/scrub/cluster.go:36 +0x208
github.com/derailed/popeye/pkg.(*Popeye).lint(0xc0002100c0)
        github.com/derailed/popeye/pkg/popeye.go:243 +0x709
github.com/derailed/popeye/pkg.(*Popeye).Lint(0xc0002100c0)
        github.com/derailed/popeye/pkg/popeye.go:184 +0x77
github.com/derailed/popeye/cmd.doIt(0xc00050c200?, {0x651638ef9af4?, 0x4?, 0x651638ef99c0?})
        github.com/derailed/popeye/cmd/root.go:76 +0xd4
github.com/spf13/cobra.(*Command).execute(0x65163a7e6040, {0xc0000522b0, 0x2, 0x2})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x867
github.com/spf13/cobra.(*Command).ExecuteC(0x65163a7e6040)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/derailed/popeye/cmd.Execute(...)
        github.com/derailed/popeye/cmd/root.go:49
main.main()
        github.com/derailed/popeye/main.go:25 +0x1b
```

**Comment by derailed** [comment]
@aschleifer v0.20.1 should be out now...

**Comment by aschleifer** [comment]
@derailed this looks much better. now it works again. Thanks for the fast fix. I will also update the Arch package to the latest version today.
