### ISSUE TITLE
Boom! runtime error: invalid memory address or nil pointer dereference (see logs)

### ISSUE THREAD

**Issue by timharris777** [derailed/popeye#286]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
For one of my clusters `popeye` gives the following error:
```
❯ popeye                                                                                                                                                                                               <aws:cfaiotnp-admin> <region:us-east-1>
 ___     ___ _____   _____                       D          .-'-.     
| _ \___| _ \ __\ \ / / __|                       O     __| K    `\  
|  _/ _ \  _/ _| \ V /| _|                         H   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  X     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /  
                                                      \_,    `    _)  
                                                         `----;  |     


Boom! runtime error: invalid memory address or nil pointer dereference (see logs)
```
logs:
```
11:11AM DBG Connecting to API Server https://<<redacted>>.us-east-1.eks.amazonaws.com
11:11AM WRN no metrics server detected No metrics-server detected
11:11AM DBG Loading raw config from flags...
11:11AM ERR runtime error: invalid memory address or nil pointer dereference
11:11AM ERR goroutine 130 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/derailed/popeye/pkg.BailOut({0x1023ed828, 0x1032d4bf0})
	github.com/derailed/popeye/pkg/helpers.go:22 +0x10c
github.com/derailed/popeye/pkg.(*Popeye).runLinter.func1()
	github.com/derailed/popeye/pkg/popeye.go:274 +0x94
panic({0x1021383c0?, 0x1032d4bf0?})
	runtime/panic.go:770 +0x124
github.com/derailed/popeye/internal/db.(*DB).FindJobs(0x1400041c108, {0x14003745560, 0x1d})
	github.com/derailed/popeye/internal/db/db.go:193 +0x33c
github.com/derailed/popeye/internal/lint.(*CronJob).checkUtilization(0x14004609e30, {0x102409878, 0x140045f1500}, 0x0, {0x14003745560?, 0x0?})
	github.com/derailed/popeye/internal/lint/cronjob.go:89 +0x48
github.com/derailed/popeye/internal/lint.(*CronJob).Lint(0x14004609e30, {0x102409878, 0x1400059e7e0})
	github.com/derailed/popeye/internal/lint/cronjob.go:47 +0x25c
github.com/derailed/popeye/internal/scrub.(*CronJob).Lint(0x1400005c830, {0x102409878, 0x1400059e7e0})
	github.com/derailed/popeye/internal/scrub/cjob.go:50 +0x334
github.com/derailed/popeye/pkg.(*Popeye).runLinter(0x14000066f00, {0x102409878?, 0x1400059e7e0?}, {{0x1400088a678, 0x11}, {0x14000134ce0, 0x5}, {0x14000134ce6, 0x2}, {0x1400000e0f0, ...}, ...}, ...)
	github.com/derailed/popeye/pkg/popeye.go:278 +0x88
created by github.com/derailed/popeye/pkg.(*Popeye).lint in goroutine 1
	github.com/derailed/popeye/pkg/popeye.go:249 +0x688
```

**Expected behavior**
I expect popeye to give the results of the scan-- and if there is an issue give a more useful error.

**Screenshots**

**Versions (please complete the following information):**
 - OS: 14.3.1 (23D60)
 - Popeye: 0.20.3
 - K8s: EKS 1.25

**Additional context**
This only happens when connected to one of my clusters. All other clusters seem to work fine.

**Comment by derailed** [comment]
@timharris777 Nice! Thank for the heads up. Let's see if we're happier on v0.20.4

**Comment by Moulick** [comment]
Made the PR https://github.com/Homebrew/homebrew-core/pull/164418
