### ISSUE TITLE
Bug when running on k8s 1.11.9

### ISSUE THREAD

**Issue by s3than** [derailed/popeye#4]
**Describe the bug**

**To Reproduce**
Run application

**Expected behavior**

**Screenshots**
See code output below

**Versions (please complete the following information):**
 - Linux
 - Popeye [0.1.3]
 - K8s [1.11.9]

**Additional context**

```
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x146b985, 0x1, 0xfffffffffffffffd, 0xc00036a76c, 0x3)
	/usr/local/Cellar/go/1.12.1/libexec/src/strings/strings.go:533 +0x5ca
github.com/derailed/popeye/internal/report.Write(0x1647f20, 0xc00061fd80, 0x2, 0x1, 0xc000288460, 0x4e)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/report/writer.go:81 +0x19c
github.com/derailed/popeye/pkg.(*Popeye).printReport(0xc000769d40, 0x7fb77196e648, 0xc0000f8240, 0xc00035ad74, 0x4)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:130 +0x7a5
github.com/derailed/popeye/pkg.(*Popeye).Sanitize(0xc000769d40)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:74 +0x4e4
github.com/derailed/popeye/cmd.doIt(0x21aa800, 0xc000203540, 0x0, 0x2)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:56 +0xdf
github.com/spf13/cobra.(*Command).execute(0x21aa800, 0xc00003a0a0, 0x2, 0x2, 0x21aa800, 0xc00003a0a0)
	/Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x21aa800, 0x0, 0x0, 0xc000381f88)
	/Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/derailed/popeye/cmd.Execute()
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:43 +0x32
main.main()
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/main.go:19 +0x20
```

**Comment by kody-abe** [comment]
Also seeing with k8s 1.11.0
